//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhanVien
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "H? và tên không ???c ?? tr?ng!")]
        [Display(Name="H? và Tên")]
        public string HoVaTen { get; set; }

        [Display(Name = "Gi?i Tính")]
        public bool GioiTinh { get; set; }

        [Required(ErrorMessage = "??a ch? không ???c ?? tr?ng!")]
        [Display(Name = "??a Ch?")]
        public string DiaChi { get; set; }

        [Display(Name = "??a Ch? Email")]
        [EmailAddress(ErrorMessage = "Email không ?úng!")]
        public string Email { get; set; }

        [Display(Name = "S? ?i?n Tho?i")]
        [Phone(ErrorMessage ="S? ?i?n tho?i không ?úng!")]
        public string SoDienThoai { get; set; }

        [Display(Name = "CMND")]
        public string CMND { get; set; }

        [Required(ErrorMessage ="Vui lòng ch?n ch?c v?.")]
        [Display(Name = "Ch?c V?")]
        public Nullable<int> IdChucVu { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
    }
}
